### ISSUE TITLE
ansible_connection in secret paths

### ISSUE THREAD

**Issue by easybe** [goethite/hashivault_vars#24]
I have `ansible_connection` set in `group_vars/all.yml`. At least in my setup `hashivault_vars` is executed before `host_group_vars`. Therefore, `ansible_connection` is not set yet when `hashivault_vars` is run, which leads to the wrong protocol being used.

I, personally, do not need to be able to have different secrets depending on the protocol. I would be happy with `/secret/ansible/hosts/hosta.example.com`. Anyway, any ideas on how to solve this? I do not want to set `ansible_connection` in Vault. I only would like to keep secrets there.

**Comment by gbevan** [comment]
Hi @easybe you should be able to move the `ansible_connection` from your group_vars/all.yml to your inventory file, e.g.:
```ini
[all]
...
[all:vars]
ansible_connection=ssh
...
```
That should be applied prior to the hashivault_vars plugin.

**Comment by gbevan** [comment]
I think you can also create a group/all entry in vault with that setting, emulating the group_vars/all

**Comment by easybe** [comment]
> I think you can also create a group/all entry in vault with that setting, emulating the group_vars/all

I would rather not do that. As I said, I would like to keep only secrets there.

Also, I would prefer to keep the the vars and the inventory separate.

**Comment by gbevan** [comment]
I could add support for an environment variable to change the behaviour, e.g.
```
HASHIVAULT_VARS_RESOLVE_CONNECTION=0
```
so, if set, it would prevent the resolving of ansible_connection in the plugin and use hosts/domains paths without the connection, like you suggest.

**Comment by easybe** [comment]
My proposal: https://github.com/goethite/hashivault_vars/pull/25
I'd be happy to get review/test feedback and update it accordingly.

**Comment by gbevan** [comment]
Cheers for that - i've taken what you did in #25 and extended to still support the original use-case and domains/fqdns, and added BATs tests for the travis tests.  Please see PR #26

**Comment by easybe** [comment]
Cool, I quickly tested your branch and it works for me, thanks.

Still, maybe the README should mention that `ansible_connection` must be set in the inventory file for secret paths containing "connection" to work reliably.

**Comment by gbevan** [comment]
#26 is merged.  0.2.0 is released to PyPI.  thx
